## Profile specific properties
spring.profiles.active=@activatedProperties@
## maven directory
maven.basedir=@project.basedir@
# Default port
server.port=8080
# Default application name
spring.application.name=api
#management.endpoints.web.exposure.include=*

# Eureka
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true