package pt.ulisboa.tecnico.socialsoftware.humanaethica.authuser.service;

import net.devh.boot.grpc.client.inject.GrpcClient;
import org.springframework.stereotype.Service;
import pt.ulisboa.tecnico.socialsoftware.humanaethica.authuser.domain.AuxUser;
import pt.ulisboa.tecnico.socialsoftware.humanaethica.proto.*;

@Service
public class AuthRemoteService {

    @GrpcClient("monolithic")
    private UserServiceGrpc.UserServiceBlockingStub userStub;

    public int createVolunteer(String name, String username, String email, String state) {
        CreateUserRequest request = CreateUserRequest.newBuilder()
                .setName(name)
                .setUsername(username)
                .setEmail(email)
                .setState(state)
                .build();

        return userStub.createVolunteer(request).getId();
    }

    public int createMember(String name, String username, String email, String state) {
        CreateUserRequest request = CreateUserRequest.newBuilder()
                .setName(name)
                .setUsername(username)
                .setEmail(email)
                .setState(state)
                .build();

        return userStub.createMember(request).getId();
    }

    public Integer createAdmin(String name, String username, String email, String state) {
        CreateUserRequest request = CreateUserRequest.newBuilder()
                .setName(name)
                .setUsername(username)
                .setEmail(email)
                .setState(state)
                .build();

        return userStub.createAdmin(request).getId();
    }



    public AuxUser getUserById(int id) {

        UserDto response = userStub.getUserById(
                GetUserRequest.newBuilder().setId(id).build()
        ); //UserDto generated by the proto file

        return new AuxUser(
                response.getId(),
                response.getUsername(),
                response.getEmail(),
                response.getRole(),
                response.getActive(),
                response.getInstitutionId(),
                response.getInstitutionActive()
        );
    }

    public String getUserState(int id) {
        return userStub.getUserState(GetUserRequest.newBuilder().setId(id).build()).getState();
    }

    public void changeState(int id, String state) {
        ChangeStateRequest request = ChangeStateRequest.newBuilder()
                .setId(id)
                .setState(state)
                .build();
        userStub.changeState(request);
    }


}
